# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - searxng

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://searxng-bng2g6hjatesdkdp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bd95c1e4860245078066165ee89ab6ed }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31fffef4fdd44db7b8c5df6aafceb0e6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: searxng-bng2g6hjatesdkdp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd95c1e4860245078066165ee89ab6ed }}/searxng:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'searxng'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b785dbb17fc64aefb7a5a72842532c81 }}
        images: 'searxng-bng2g6hjatesdkdp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd95c1e4860245078066165ee89ab6ed }}/searxng:${{ github.sha }}'